import type { Employee } from '../types/employee';

export type {
  Employee,
  EmployeeId,
  EmployeeRiskLevel,
  EmployeeStatus,
  EmployeeSummaryMetrics,
  ISODateString,
  NewEmployeeInput,
} from '../types/employee';
export type {
  DashboardFilters,
  DateRange,
  EmployeeRiskLevelFilter,
  EmployeeStatusFilter,
  FilterAllOption,
} from '../types/filters';
export type {
  ChartSegment,
  DashboardState,
  DashboardStats,
  Department,
  DepartmentSummary,
  KpiCardModel,
  KpiChangeDirection,
  KpiIconName,
  LineChartData,
  Role,
  RoleSummary,
  SkillGap,
} from '../types/dashboard';

export const mockEmployees: Employee[] = [
  {
    id: 'EMP-001',
    name: 'Sanjay Kumar',
    email: 'sanjay.kumar@example.com',
    department: 'Engineering',
    role: 'Frontend Engineer',
    status: 'Active',
    riskLevel: 'Low',
    joinedDate: '2025-01-15',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sanjay',
    location: 'Chennai',
  },
  {
    id: 'EMP-002',
    name: 'Rohith Sharma',
    email: 'rohith.sharma@example.com',
    department: 'Engineering',
    role: 'Backend Engineer',
    status: 'Active',
    riskLevel: 'Medium',
    joinedDate: '2024-03-12',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rohith',
    location: 'Bangalore',
  },
  {
    id: 'EMP-003',
    name: 'Dhoni Singh',
    email: 'dhoni.singh@example.com',
    department: 'Engineering',
    role: 'Fullstack Engineer',
    status: 'Active',
    riskLevel: 'High',
    joinedDate: '2024-08-20',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dhoni',
    location: 'Hyderabad',
  },
  {
    id: 'EMP-004',
    name: 'Virat Patel',
    email: 'virat.patel@example.com',
    department: 'Design',
    role: 'Product Designer',
    status: 'Active',
    riskLevel: 'Low',
    joinedDate: '2025-05-10',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Virat',
    location: 'Pune',
  },
  {
    id: 'EMP-005',
    name: 'Hardik Rao',
    email: 'hardik.rao@example.com',
    department: 'Product',
    role: 'Product Manager',
    status: 'Active',
    riskLevel: 'Medium',
    joinedDate: '2023-11-01',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hardik',
    location: 'Bangalore',
  },
];
